name: crime_alert
description: A Crime Alert Application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.1
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  json_serializable: ^4.1.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  google_sign_in: ^5.0.5
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  cloud_firestore: ^2.4.0
  flutter_bloc: ^7.0.1
  equatable:
  location:
  geolocator:
  image_picker_gallery_camera: ^0.2.2
  package_info: ^2.0.2
  another_flushbar: ^1.10.24
  firebase_storage: ^10.0.1
  flutter_geocoder: ^0.2.2-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
